export type ValidSkills =
  | "Next.js"
  | "React"
  | "GraphQL"
  | "Nest.js"
  | "express.js"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "React Native"
  | "Angular"
  | "Redux"
  | "Socket.io"
  | "Material UI"
  | "Tailwind CSS"
  | "AWS"
  | "Bootstrap"
  | "Google Auth"
  | "MySQL"
  | "Java"
  | "Databricks"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "Redis"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "FastAPI"
  | "Django"
  | "Vue.js"
  | "Sass"
  | "Firebase"
  | "Azure"
  | "Google Cloud"
  | "Figma"
  | "Webpack"
  | "Jest"
  | "Cypress"
  | "Storybook"
  | "Prisma"
  | "Supabase"
  | "Vercel"
  | "Netlify"
  | "Three.js"
  | "WebGL"
  | "TensorFlow"
  | "PyTorch"
  | "Spring Boot"
  | "Laravel"
  | "PHP"
  | "Flutter"
  | "Dart"
  | "Flask"
  | "Django"
  | "FastAPI"
  | "SQL"
  | "NoSQL"
  | "Framer Motion"
  | "ROS2"
  | "PX4"
  | "C++"
  | "MATLAB"
  | "Simulink"
  | "Machine Learning"
  | "Computer Vision"
  | "Reinforcement Learning"
  | "Swarm Robotics"
  | "Control Systems"
  | "UAVs"
  | "Embedded Systems"
  | "Arduino"
  | "ESP32"
  | "OpenAI Gym"
  | "Gazebo"
  | "SLAM"
  | "Verilog"
  | "SolidWorks"
  | "Vivado"
  | "Linux"
  | "Bash"
  | "NumPy"
  | "Pandas"
  | "Matplotlib"
  | "Selenium"
  | "Playwright"
  | "Web Scraping"
  | "Data Analysis"
  | "Deep Learning"
  | "Computer Architecture"
  | "Assembly"
  | "Systems Programming";

export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "3D Modeling"
  | "AI/ML"
  | "Robotics"
  | "Computer Vision"
  | "Systems";

export type ValidExpType = "Software" | "Robotics" | "Research" | "Academic";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "contact"
  | "resume";
