export const siteConfig = {
  name: "Anuj Patil | Software Developer × Robotics Engineer",
  authorName: "Anuj Vijay Patil",
  username: "AnujPatil110377",
  description:
    "Anuj Patil's developer portfolio - Building intelligent software for autonomous robots. Full-stack developer and robotics engineer at IIT Jodhpur, creating cutting-edge applications for drone navigation, ROS2 ecosystems, computer vision, and AI-driven robotics systems.",
  url: "https://myportfolio707.netlify.app",
  links: {
    twitter: "https://x.com/AnujPatil110377",
    github: "https://github.com/AnujPatil110377",
  },
  ogImage: "https://myportfolio707.netlify.app/profile-img.jpg",
  iconIco: "/favicon.ico",
  logoIcon: "/profile-img.jpg",
  keywords: [
    "Anuj Patil",
    "Anuj Vijay Patil",
    "Robotics Engineer",
    "AI/ML Developer",
    "IIT Jodhour",
    "ROS2",
    "PX4",
    "Autonomous Systems",
    "Drone Navigation",
    "Computer Vision",
    "Reinforcement Learning",
    "Swarm Robotics",
    "Embedded Systems",
    "UAV Programming",
    "SLAM",
    "ESP32",
    "Flutter Development",
    "Machine Learning",
    "Deep Learning",
    "Control Systems",
    "Gazebo Simulation",
    "MATLAB",
    "C++ Programming",
    "Full Stack Development",
    "React.js",
    "Next.js",
    "Python Programming",
    "Embedded Software",
    "Mobile App Development",
    "Web Applications",
    "Software Architecture",
    "API Development",
  ],
};
